// Generated by CoffeeScript 1.3.3
(function() {
  var Pages, beautify;

  beautify = require("./beautify");

  Pages = {
    page: function(options) {
      var body, css, javascript, meta;
      javascript = options.javascript, css = options.css, body = options.body, meta = options.meta;
      return beautify(this.doctype() + this.html.html([this.html.head([this.meta(meta), this.javascript(javascript), this.css(css)]), this.html.body(body)]));
    },
    doctype: function() {
      return "<!DOCTYPE html>";
    },
    meta: function() {
      return "";
    },
    javascript: function(scripts) {
      var script;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = scripts.split(" ");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          script = _ref[_i];
          _results.push(this.html.script({
            src: this.javascript_files[script],
            type: "text/javascript"
          }));
        }
        return _results;
      }).call(this)).join(" ");
    },
    css: function(stylesheets) {
      var stylesheet;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = stylesheets.split(" ");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stylesheet = _ref[_i];
          _results.push(this.html.link({
            href: this.css_files[stylesheet],
            type: "text/css",
            rel: "stylesheet"
          }));
        }
        return _results;
      }).call(this)).join("");
    }
  };

  module.exports = Pages;

}).call(this);
