// Generated by CoffeeScript 1.3.3
(function() {
  var Bootstrap;

  Bootstrap = (function() {

    function Bootstrap(options) {
      if ((options != null ? options.html : void 0) != null) {
        this.html = options.html;
      }
    }

    Bootstrap.prototype.header = function(content) {
      return this.html.div({
        "class": "page-header",
        content: content
      });
    };

    Bootstrap.prototype.navbar = function(options) {
      var classes;
      classes = ["navbar"];
      if (options.inverse != null) {
        classes.push("navbar-inverse");
      }
      if (options.fixed_top != null) {
        classes.push("navbar-fixed-top");
      }
      return this.html.div({
        "class": classes.join(" "),
        content: this.html.div({
          "class": "navbar-inner",
          content: this.container(options.content)
        })
      });
    };

    Bootstrap.prototype.brand = function(name) {
      return this.html.a({
        href: "/",
        "class": "brand",
        content: name
      });
    };

    Bootstrap.prototype.navmenu = function(items) {
      var item;
      return this.html.ul({
        "class": "nav",
        content: (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            item = items[_i];
            _results.push(this.html.li({
              "class": (item.active != null ? "active" : void 0),
              content: this.html.a({
                href: item.url,
                content: item.text
              })
            }));
          }
          return _results;
        }).call(this)
      });
    };

    Bootstrap.prototype.navtabs = function(tabs) {
      var id, tab;
      return this.html.div({
        "class": "tabbable",
        content: [
          this.html.ul({
            "class": "nav nav-tabs",
            content: (function() {
              var _results;
              _results = [];
              for (id in tabs) {
                tab = tabs[id];
                _results.push(this.html.li({
                  "class": [tab.active != null ? "active" : void 0],
                  content: this.html.a({
                    href: "#" + id,
                    "data-toggle": "tab",
                    text: tab.label
                  })
                }));
              }
              return _results;
            }).call(this)
          }), this.html.div({
            "class": "tab-content",
            content: (function() {
              var _results;
              _results = [];
              for (id in tabs) {
                tab = tabs[id];
                _results.push(this.html.div({
                  "class": ["tab-pane fade in", tab.active != null ? "active" : void 0],
                  id: id,
                  content: tab.content
                }));
              }
              return _results;
            }).call(this)
          })
        ]
      });
    };

    Bootstrap.prototype.container = function(items) {
      return this.html.div({
        "class": "container",
        content: items
      });
    };

    Bootstrap.prototype.hero = function(items) {
      return this.html.div({
        "class": "hero-unit",
        content: items
      });
    };

    Bootstrap.prototype.row = function(items) {
      return this.html.div({
        "class": "row",
        content: items
      });
    };

    Bootstrap.prototype.column = function(width, items) {
      return this.html.div({
        "class": "span" + width,
        content: items
      });
    };

    Bootstrap.prototype.button = function(options) {
      var classes;
      classes = ["btn"];
      if (options.primary != null) {
        classes.push("btn-primary");
      }
      if (options.large != null) {
        classes.push("btn-large");
      }
      return this.html.a({
        href: options.url,
        text: options.text,
        "class": classes.join(" ")
      });
    };

    return Bootstrap;

  })();

  module.exports = Bootstrap;

}).call(this);
